### ISSUE TITLE
[Non-issue] Sub-groupes

### ISSUE THREAD

**Issue by d0ob** [ZengineerIO/factorio-evenmoretextplates#2]
Hi there !

I wonder if it's possible to organize the text plates differently ? 
For both your extension and the base mod, I'd like to have two rows, one for each size. 
My coding knowledge being just enough to make basic and dirty changes, my attempts get me nowhere.. ^^

**Comment by ZengineerIO** [comment]
Hey, sorry for my late reply. 

Here's a [gist](https://gist.github.com/ZengineerIO/1319dc5649395f40f7e24b64b197ec5b) that should do the trick. Just add it as a seperate mod.
Now seeing the order I like it and might add it at some point with a setting to enable the new order. 

Thank you for your suggestion :sunglasses:

**Comment by d0ob** [comment]
Hi =)  No problem.
Thanks to you, it works flawlessly ! 
I think it is better like that =3  And I agree, a setting would be a good idea.

Well, I could have another suggestion then, if you want it ^^ Put the plates inside the Dectorio's group, if the mod is installed.

This time I was able to do it myself, and I think it fits nicely ! I've also put other things inside this group ^^ Display plates for example. (I can't remember in fact, this time it's maybe the mod that do it by itself already.) There isn't much in it by default so there is place, and that way it declutters some other groups that are much solicited by mods ! (Thought, I don't know if modders are comfortable putting their items inside other mod's groups, that's maybe "modder rudeness" I don't know x)

**Comment by ZengineerIO** [comment]
Thanks, I forgot about the Dectorio case. Texplates already puts them there, but my new subgroup "texplates-small" was missing the dectorio adjustment if available. I've updated the gist accordingly.

**Comment by d0ob** [comment]
Oh, so it is Textplates and not Displayplates that have the Dectorio placement already ! (Or maybe both, in fact, really can't remember...) Well, that close the question indeed ^^ Thus, is my "craft inventory OCD" pleased lol

**Comment by ZengineerIO** [comment]
It's indeed both that do that, see [here](https://github.com/Wyrrrd/IndustrialDisplayPlates/blob/master/data-updates.lua).
I'm happy your OCD got pleased. :slightly_smiling_face:

**Comment by d0ob** [comment]
Thanks ^^ 
Oh that's interesting to see how it's done ! Wouldn't have bet it was that straightforward lol
That's cool you thought about looking and sharing, thanks !
