### ISSUE TITLE
Crash when loading with Textplates 0.6.5

### ISSUE THREAD

**Issue by robot256** [ZengineerIO/factorio-evenmoretextplates#3]
`   1.335 Error ModManager.cpp:1558: Failed to load mod "textplates": __textplates__/prototype/technology.lua:1: bad argument #1 of 2 to 'pairs' (table expected, got nil)
stack traceback:
	[C]: in function 'pairs'
	__textplates__/prototype/technology.lua:1: in main chunk
	[C]: in function 'require'
	__textplates__/data-updates.lua:1: in main chunk`

Some data was added to the `textplates` global table in the data phase (at least the `technologies` table, maybe more) that is not being preserved when Even More Textplates adds data to it.  Thus Textplates crashes looking for that member.

**Comment by ZengineerIO** [comment]
Thanks for the info. It's fixed with the next update.
